blog/blog/urls.py
from django.conf.urls import url ,include
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^',include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^adminpanel/', include('adminpanel.urls')),
    url(r'^adminpanel/', include('adminpanel.urls',namespace='adminpanel')),
    url(r'^main/',include('main.urls')),
    url(r'^admin/', include('adminpanel.urls')),
    url(r'^home/', include('main.urls')),
    url(r'^accounts/', include("accounts.urls", namespace= 'accounts') ),
    #url(r'^accounts/', include('django.contrib.auth.urls')),

    #url(r'^adminpanel/', include("adminpanel.urls", namespace="adminpanel") ),

    #url(r'^accounts/', include('django.contrib.auth.urls')),
]

blog/main/urls.py
from django.conf.urls import url
import views


urlpatterns = [
    url(r'^.$',views.homePosts),
    url(r'^$',views.homePosts , name='homeurl'),
    url(r'^subscribe/(?P<cat_id>[0-9]+)/$' , views.subscribe),
    url(r'^unsubscribe/(?P<cat_id>[0-9]+)/$' , views.unsubscribe),
    url(r'^select/(?P<model_name>[a-zA-Z]+)/$', views.modelSelect),
    #url(r'^$',views.sidebar),
    url(r'^(?P<id>[0-9]+)/post$', views.PostDetails),
    url(r'^(?P<postID>[0-9]+)/addComment$', views.addComment),
    url(r'^(?P<postID>[0-9]+)/(?P<commentID>[0-9]+)/addReply$', views.addReply),
    url(r'^(?P<postID>[0-9]+)/(?P<commentID>[0-9]+)/deleteComment$', views.deleteComment),
    url(r'^category/(?P<cat_id>[0-9]+)/posts$', views.category_posts),
    

]

blog/main/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

#Categories table
class category(models.Model):
    cat_title = models.CharField(max_length= 200)
    user = models.ManyToManyField(User, blank=True)

    def __str__ (self):
        return self.cat_title


#Posts table
class post(models.Model):
    post_title = models.CharField(max_length = 200)
    post_content = models.TextField()
    post_views = models.IntegerField(default=0)
    feature_status = models.BooleanField(default=0)
    post_img=models.ImageField(upload_to="./static/media/", blank=True)
    post_date=models.DateField(auto_now_add = True)
    post_cat_id=models.ForeignKey(category)

    def __str__ (self):
        return self.post_title

    def __str__(self):
        return self.post_title

#Comments table
class comment(models.Model):
    comment_body = models.TextField()
    comment_date=models.DateField(auto_now_add = True)
    comment_user_id=models.ForeignKey(User)
    reply_comment_id = models.ForeignKey('self', null=True, blank=True)
    comment_post_id = models.ForeignKey(post)
    def __str__ (self):
        return self.comment_body

    def __str__(self):
        return self.comment_body

# Words list table
class word_list(models.Model):
    word_list = models.CharField(max_length=50)

    def __str__ (self):
        return self.word_list


    def __str__(self):
        return self.word_list
#    cat_id = models.ForeignKey(category)
#    user_id = models.ForeignKey(User)

blog/main/forms.py
from django import forms
from models import comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = comment
        fields = ('comment_body',)
        #exclude = ['comment_user_id','reply_comment_id','comment_post_id',]

blog/main/views.py
from django.contrib.sites import requests
from django.shortcuts import render , render_to_response, redirect,  get_list_or_404, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import auth
from forms import CommentForm
from models import post , comment , word_list ,category
from django.contrib.auth.models import User
import random
import re
# Create your views here.
class OffensiveWordsFilter(object):
    def __init__(self, filterlist, ignore_case=True, replacements="$@%-?!", complete=True, inside_words=False):
        self.badwords = filterlist
        self.ignore_case = ignore_case
        self.replacements = replacements
        self.complete = complete
        self.inside_words = inside_words

    def _make_clean_word(self, length):
        return ''.join([random.choice(self.replacements) for i in
                  range(length)])

    def __replacer(self, match):
        value = match.group()
        if self.complete:
            return self._make_clean_word(len(value))
        else:
            return value[0]+self._make_clean_word(len(value)-2)+value[-1]

    def clean(self, text):
        regexp_insidewords = {
            True: r'(%s)',
            False: r'\b(%s)\b',
            }

        regexp = (regexp_insidewords[self.inside_words] %
                  '|'.join(self.badwords))

        r = re.compile(regexp, re.IGNORECASE if self.ignore_case else 0)

        return r.sub(self.__replacer, text)

def wordsCleaner(sentence):
    badwords = word_list.objects.values_list('word_list', flat=True)
    if badwords.exists():
        owf = OffensiveWordsFilter(badwords, replacements="*")
        #print f.clean(sentence)
        owf.inside_words = True
        #print f.clean(sentence)
        owf.complete = False
        #print f.clean(sentence)
        return owf.clean(sentence)
    else:
        return sentence

def homePosts (request):
    posts = post.objects.all().order_by('-post_date')
    feature_posts = post.objects.filter(feature_status=True)[:5]
    categories = category.objects.all()

    paginator = Paginator(posts , 5 )
    page = request.GET.get('page')
    try:
        posts_data = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts_data = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts_data = paginator.page(paginator.num_pages)
    current_user = request.user
    subscribed_cats = category.objects.filter(user = current_user.id)
    context = {'posts': posts_data , 'feature_posts': feature_posts, 'categories': categories, "subscribedCats": subscribed_cats }
    return render(request , 'main/home.html' , context)

import smtplib

from email.mime.text import MIMEText

def confirmSubscription(current_user, Category):
    fName='Beloved'
    lName='Member'
    lambda fName: current_user.first_name if current_user.first_name != None else 'Beloved'
    lambda lName: current_user.last_name if current_user.last_name  != None else 'Member'
    textMsg = "Dear "+fName+" "+lName+" ("+current_user.username+"): you have subscribed to new category "
    msg = MIMEText(textMsg+Category)
    msg['Subject'] = "Hello"+current_user.first_name+" "+current_user.last_name+" ("+current_user.username+"), we heve news for you"
    msg['From'] = "khogaeslam@gmail.com"
    msg['To'] = current_user.email

    s = smtplib.SMTP('smtp.mailgun.org', 587)

    s.login('postmaster@sandboxa9f988908bd44b8892f62e305b8c7572.mailgun.org', '7edcbf92ebdd1f395dd01deee3d4d3f7')
    s.sendmail(msg['From'], msg['To'], msg.as_string())
    s.quit()

def subscribe(request, cat_id):
    current_user = request.user
    subscribed_cats = category.objects.get(id = cat_id)
    subscribed_cats.user.add(current_user)
    confirmSubscription(current_user,subscribed_cats.cat_title)
    return HttpResponseRedirect('/home')

def unsubscribe(request, cat_id):
    current_user = request.user
    subscribed_cats = category.objects.get(id = cat_id)
    subscribed_cats.user.remove(current_user)
    return HttpResponseRedirect('/home')

def modelSelect(request, model_name):
    if (model_name == "category" or model_name == "post" or model_name == "word_list" or model_name == "User"):
        objs = eval(model_name).objects.all()
        return render(request, 'main/list.html', {"objs", objs})
    else:
        return HttpResponseRedirect("/admin")

def PostDetails(request, id):
    #return HttpResponse('details of %s' %id)
    postDetails =  get_object_or_404(post, id = id)
    categoryDetails = postDetails.post_cat_id
    post_views_num  = postDetails.post_views + 1
    postDetails .post_views = post_views_num
    postDetails.save()
    #comments = comment.objects.filter(comment_post_id = postDetails.id)
    form = CommentForm(request.POST or None)

    context = {'postDetails': postDetails, 'postCat': categoryDetails, 'form': form}
    return render(request, 'post/postDetails.html', context )

def addComment(request, postID):
    print postID, request.user
    if request.method == 'POST':
	    comment = CommentForm(request.POST, request.FILES)
	    if comment.is_valid():
		    comment = comment.save(commit=False)
            comment.comment_body = wordsCleaner(comment.comment_body)
            comment.post = post.objects.get(id = postID)
            #comment.User = User.objects.get(id = request.user.id)
            comment.comment_user_id_id = request.user.id
            comment.comment_post_id_id = postID

            comment.save()
            return redirect(request.path)
    return HttpResponseRedirect("/main/"+postID+"/post")

def addReply(request, postID, commentID):
    if request.method == 'POST':
	    reply = CommentForm(request.POST, request.FILES)
	    if reply.is_valid():
		    reply = reply.save(commit=False)
            reply.comment_body = wordsCleaner(reply.comment_body)
            reply.post = post.objects.get(id = postID)
            #comment.User = User.objects.get(id = request.user.id)
            reply.comment_user_id_id = request.user.id
            reply.comment_post_id_id = postID
            reply.reply_comment_id = comment.objects.get(id = commentID)

            reply.save()
            return redirect(request.path)
    return HttpResponseRedirect("/main/"+postID+"/post")

def deleteComment(request, postID, commentID):
    comment.objects.filter(reply_comment_id=commentID).delete()
    comment.objects.filter(id=commentID).delete()
    return HttpResponseRedirect("/main/"+postID+"/post")

def category_posts(request,cat_id):
    cat_post = post.objects.filter(post_cat_id_id=cat_id)
    paginator = Paginator(cat_post , 5 )
    page = request.GET.get('page')
    try:
        posts_data = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts_data = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts_data = paginator.page(paginator.num_pages)
    current_user = request.user
    context = {'catposts':cat_post,'posts': posts_data  }

    return render (request , 'post/catPosts.html' , context)

blog/main/templates/post/catPosts.html
{%  extends 'main/base.html' %}
 {% load staticfiles %}
    {% block title %}
      <title> Blog| Home</title>
    {% endblock %}
    {% block main_block %}


        <div class="blog-left">
          <div class="blog-left-grid">
            {% if posts %}
              {% for post in posts %}
              <div class="blog-left-grid-left" style="padding-top: 30px;">
                  <h3><a href="{{BASE_DIR}}/main/{{ post.id }}/post">{{post.post_title}}</a></h3>
                  <p>by <span>Admin</span> | {{post.post_date}} <p class="post-views"> <i class="fa fa-eye" aria-hidden="true"></i>
   {{post.post_views }} views</p> </p>
                </div>
                <div class="blog-left-grid-right">
                  <a href="#" class="hvr-bounce-to-bottom non">{{post.comment_set.count}} Comments</a>
                </div>
                <div class="clearfix"> </div>
                <a href="{{BASE_DIR}}/main/{{ post.id }}/post"><img src="{{BASE_DIR}}/{{post.post_img}}" alt=" " class="img-responsive" /></a>
                <p class="para"> {{post.post_content|truncatewords:30}}</p>
                <div class="rd-mre">
                  <a href="{{BASE_DIR}}/main/{{ post.id }}/post" class="hvr-bounce-to-bottom quod">Read More</a>
                </div>

                   {% endfor %}
              {% else %}
              <p> There are no posts at this category </p>
             {% endif %}
          </div>
          <div class="pagination">
              <span class="step-links">
                  {% if posts.has_previous %}
                      <a class="btn btn-primary" href="?page={{ posts.previous_page_number }}">previous</a>
                  {% endif %}

                  <span class="current">
                      Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                  </span>

                  {% if posts.has_next %}
                      <a class="btn btn-primary" href="?page={{ posts.next_page_number }}">next</a>
                  {% endif %}
              </span>
          </div>
        </div>


{% endblock %}

blog/main/templates/post/postDetails.html
{%  extends 'main/base.html' %}
  {% block title %}
   <title> {{postDetails.post_title}} </title>
  {% endblock %}
{% load staticfiles %}
  {% block main_block %}
  <script>
  $(function() {
        $(".addComment textarea").attr('placeholder', 'Write a comment' );
          $(".addReply textarea").attr('placeholder', 'Write a reply' );
    });
</script>
    <h1 style="margin-bottom: 30px;">{{ postDetails.post_title }}</h1>
    <p>Category : <a href="/category/{{postCat.id}}/details">{{postCat.cat_title}}</a></p>
    <p>Date: {{postDetails.post_date}}</p>
    <img src="{{BASE_DIR}}/{{postDetails.post_img}}" style="width: 100%" >
    <article style="margin-top:30px;">{{postDetails.post_content}}</article>



    {% if postDetails.comment_set.all %}
    <h2>Comments</h2>
    <div class="comments">
        {% for comment in postDetails.comment_set.all %}
          {% if not comment.reply_comment_id %}
            <div class="comment">
               <p class="user-profile"> <img style="width: 50px" class= "profile-picture" src= {% static "images/co.png" %}> </p>
               <div class="comment-container">
                <p class= "user-name"> {{ comment.comment_user_id }} : </p>
                  <p> {{ comment.comment_body }} </p>
                  <p class="comment-info" > said on {{ comment.comment_date }} </p>
                    {% ifequal request.user.id comment.comment_user_id.id %}
                        <a href="{{BASE_DIR}}/home/{{ postDetails.id }}/{{ comment.id }}/deleteComment">delete</a>
                    {% endifequal %}
              </div>
            </div>
            <div class="reply">
                {% for reply in comment.comment_set.all %}
                <div>
                      <p class="user-profile"> <img style="width: 50px" class= "profile-picture" src= {% static "images/co.png" %}> </p>
                      <div class="comment-container">
                       <p class= "user-name"> {{ reply.comment_user_id }} : </p>
                         <p> {{ reply.comment_body  }} </p>
                         <p class="reply-info"> said on {{ reply.comment_date }} </p>
                            {% ifequal request.user.id reply.comment_user_id.id %}
                                <a href="{{BASE_DIR}}/home/{{ postDetails.id }}/{{ reply.id }}/deleteComment">delete</a>
                            {% endifequal %}
                      </div>
                </div>

                {% endfor %}
                {% if request.user.is_authenticated %}
               <form class="addReply" method="POST" action="{{BASE_DIR}}/home/{{ postDetails.id }}/{{ comment.id }}/addReply"> {% csrf_token %}
                 <label for="{{ form.comment_body.id_for_label }}"></label>
               {{ form.comment_body }}
                   <input type='submit' class="btn btn-primary" value='Reply'>
               </form>

               {% else %}
               {% endif %}
               </div>
          {% endif %}
        {% endfor %}
    {% endif %}
  </div>
    {% if request.user.is_authenticated %}
   <form class="addComment" method="POST" action="{{BASE_DIR}}/home/{{ postDetails.id }}/addComment"> {% csrf_token %}
     <label for="{{ form.comment_body.id_for_label }}"></label>
   {{ form.comment_body }}
       <input type='submit' class="btn btn-primary" value='Comment'>
   </form>
   {% else %}
   {% endif %}

  {% endblock %}